(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["BipedalLocomotion`Model`", {"GlobalVariables`", "Derivatives`", "RigidBodyDynamics`", "BipedalLocomotion`", "HybridDynamics`"}]

Begin["`Private`"]


(* ::Input::Initialization:: *)
BLWalk[A_Association, k_?VectorQ, n_:1, opts:OptionsPattern[]] := If[KeyExistsQ[A, k], BLWalk[A[k, "c"][[1]], n, opts], Message[BLWalk::k, "Key", k, Keys@A]];

BLWalk[A_Association, k_Integer, n_:1, opts:OptionsPattern[]] := If[Length@A > k, BLWalk[A[[k, "c", 1]], n, opts], Message[BLWalk::k, "Index", k, "1 <= k <= " <> ToString@Length@A]];


(* ::Input::Initialization:: *)
End[]
EndPackage[]
