(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["BipedalLocomotion`", {"GlobalVariables`", "RigidBodyDynamics`", "HybridDynamics`", "BipedalLocomotion`Model`"}]

Begin["`Private`"]


(* ::Input::Initialization:: *)
Options[BLP] = {BLMap -> {}, BLSim -> BLSim};

BLP[cp_, opts:OptionsPattern[]] := BLP[BLbiped["m[0]"], cp, opts]["R"];

BLP[mp_String, cp_, opts:OptionsPattern[]] := Module[{xT, xT0,  M, R},
(* apply step map using a wrapper for BLMap *)
M = OptionValue[BLSim][mp, cp, OptionValue[BLMap]];

(* devec state, parameters, and modes at switching times *)
M["c"] = SparseArray /@ M["c"];
M["x-"] = SparseArray /@ M["x-"];
M["x+"] = SparseArray /@ M["x+"];
M["a-"] = SparseArray /@ M["a-"];
M["a+"] = SparseArray /@ M["a+"];

M["c"] = devec[#, nc]& /@ M["c"];
M["x-"] = devec[#, nx]& /@ M["x-"];
M["x+"] = devec[#, nx]& /@ M["x+"];
M["a-"] = devec[#]& /@ M["a-"];
M["a+"] = devec[#]& /@ M["a+"];

(* is it a gait? *)
xT = M["x-"][[-1]];
xT0 = M["c"][[-1, All, 1;;nx]];

R = BLbiped["c", mp, "x"];
R = xT[[All, R]] - xT0[[All, R]];
R[[1]] = SparseArray@BLState[R[[1]]];

Join[M, <|"R" -> R, "p" -> SparseArray@cp|>]
];


(* ::Input::Initialization:: *)
End[]
EndPackage[]
