(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["BipedalLocomotion`"]


(* ::Input::Initialization:: *)
BLFoot::usage = "";
BLSwingFootPosition::usage = "";
BLStanceFootPosition::usage = "";
BLSwingFootHeight::usage = "";
BLKnees::usage = "";
BLStep::usage = "";
BLAverageVelocity::usage = "";
BLSlope::usage = "";
BLApplyBounds::usage = "";
BLStateBounds::usage = "";
BLqddfu::usage = "";
BLqdd::usage ="";
BLf::usage = "";
BLu::usage = "";
BLFriction::usage = "";
BLqd\[Iota]::usage = "";
BLqd::usage = "";
BL\[Iota]::usage = "";
BLcost::usage = "";
BLuu::usage = "";
BLuBMqd::usage = "";
BLuinuin::usage = "";
BLuinMqd::usage = "";
BLR\[Sigma]::usage = "";
BLL\[Sigma]::usage = "";BLV\[Sigma]::usage = "";


(* ::Input::Initialization:: *)
BLAlternateCompile::usage = "";
BLAlternateCompileBiped::usage = "";
BLAlternateCompileWithInputSpline::usage = "";


(* ::Input::Initialization:: *)
CompileDeBoor::usage = "";
CompileWithInputSpline::usage = "";
KnotsDTT::usage = "";
SplineSim::usage = "";
BLSplineSim::usage = "";


(* ::Input::Initialization:: *)
BLApplyBounds2::usage = "";
BLFunc::usage = "";
BLApplyBoundsAux::usage = "";


(* ::Input::Initialization:: *)
OptimalityConstraints::usage = "";
FirstOrderOptimalityCondition::usage = "";
EffortOptimalityConstraints::usage = "";
FArcLength::usage = "";


(* ::Input::Initialization:: *)
Begin["`Private`"]


(* ::Input::Initialization:: *)
End[]
EndPackage[]


(* ::Input::Initialization:: *)
BeginPackage["ContinuationMethods`"]


(* ::Input::Initialization:: *)
BifurcationPointTest::usage = "";


(* ::Input::Initialization:: *)
MoreThuente::usage = "";
Armijo::usage = "";


(* ::Input::Initialization:: *)
cmc::usage = "";
cmroot::usage = "";
cmac::usage = "";
cmnat::usage = "";

StepPlot::usage = "";


(* ::Input::Initialization:: *)
tmon::usage = "";
rootmon::usage = "";
hmon::usage = "";
plotmon::usage = "";

Man0::usage = "";
Mani::usage = "";
Man::usage = "";


(* ::Input::Initialization:: *)
Begin["`Private`"]


(* ::Input::Initialization:: *)
End[]
EndPackage[]


(* ::Input::Initialization:: *)
BeginPackage["Options`"]
MergeOpts::usage = "";
ComputeBounds::usage = "";
Timer::usage = "";
Sparse::usage = "";
Begin["`Private`"]
End[]
EndPackage[]


(* ::Input::Initialization:: *)
BeginPackage["HybridDynamics`"]
\[CurlyPhi]aux::usage = "";
Begin["`Private`"]
End[]
EndPackage[]
